# Generated by Django 4.2.11 on 2026-06-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tideevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('activity', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_min', models.IntegerField()),
                ('category', models.CharField(choices=[('Core', 'AI Dev — Core OS'), ('macOS', 'AI Dev — macOS Native'), ('Business', 'AI Dev — Business Data'), ('Tools', 'AI Dev — Tools/Scripts'), ('Physical', 'Physical'), ('Meta', 'Meta / Admin'), ('Recovery', 'Recovery')], max_length=20)),
                ('is_anchor', models.BooleanField(default=False, help_text='Muay Thai / immovable blocks')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Schedule Block',
                'verbose_name_plural': 'Schedule Blocks',
                'ordering': ['day_of_week', 'display_order', 'start_time'],
            },
        ),
    ]
